### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by christophelimpalair** [fugue/emulambda#14]
Is there any way to pass in custom profiles for different credentials? For example, say I have different profiles in ~/.aws/credentials. As of right now, emulambda assumes the default profile and I haven't found a way of using another profile.

Thanks!

**Comment by sebsto** [comment]
There is no dependencies / usage of AWS API from emulambda point of view.  In other words, emulambda do not use any AWS API and hence is independant to profiles.

If your lambda function code makes some AWS API call, you can rely on standard Boto behavior to locate credentials, including "Assume Role Provider" as described in http://boto3.readthedocs.org/en/latest/guide/configuration.html 

Beware, this will not be portable to the real Lambda execution environment as the ~/.aws credential file and profiles will not exists there.

Nice solution would be to have emulambda to implement this feature request : https://github.com/fugue/emulambda/issues/7

**Comment by simonhanmer** [comment]
@christophelimpalair I had a similar problem and wanted to emulate the use of different roles with lambda and not having to change profiles etc - I've put together a blog post on my solution at https://simonhanmer.co.uk/unique-credentials-local-lambda/

**Comment by dom-at-fugue** [comment]
Since we merge #7, I'm going to mark this as resolved. Ping me if we need to look at this further.
