### ISSUE TITLE
Local pip install

### ISSUE THREAD

**Issue by DeviaVir** [fugue/emulambda#15]
I was running into problems trying to install locally, specifically:

```
 ✘ deviavir  ~/Downloads/emulambda  pip install -e emulambda
Directory 'emulambda' is not installable. File 'setup.py' not found.
 ✘ deviavir  ~/Downloads/emulambda  sudo pip install -e emulambda
Password:
Directory 'emulambda' is not installable. File 'setup.py' not found.
```

I could finally get it installed with the following syntax:
```
✘ deviavir  ~/Downloads/emulambda  pip install -e .
[..]
Successfully installed emulambda hurry.filesize-0.9 nose-1.3.7 numpy-1.10.4
```

Might be worth adding this to the wiki. I'm on `Mac OS X 10.11 15A279b`, and:
```
 deviavir  ~  python --version
Python 2.7.11
 deviavir  ~  pip --version
pip 8.1.0 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

It might be an even better idea to get this project up and running on [PyPi](https://packaging.python.org/en/latest/distributing/#uploading-your-project-to-pypi).

**Comment by sebsto** [comment]
This is the expected behavior of ``pip -e`` option.

**Comment by DeviaVir** [comment]
@sebsto maybe so, I was just following installation instructions: https://github.com/fugue/emulambda/blob/master/README.md#installation

**Comment by bacoboy** [comment]
Just ran into this on a mac.  The README wasn't update.  How come it was close?
