### ISSUE TITLE
Use custom IAM policy for running lambda function

### ISSUE THREAD

**Issue by wayne-luminal** [fugue/emulambda#7]
When creating a lambda function, you must specify an IAM role for it. emulambda should assume the role before running the function.

**Comment by sebsto** [comment]
I just submitted a pull request to support Lambda Execution Role.  See https://github.com/fugue/emulambda/pull/16

While waiting for this to be merged, you can test and provide feedback from my forked repo : https://github.com/sebsto/emulambda/

**Comment by dom-at-fugue** [comment]
Since we merged that, I think this issue is resolved.
